export const userConstants = {
    REGISTER_REQUEST: 'USERS_REGISTER_REQUEST',
    REGISTER_SUCCESS: 'USERS_REGISTER_SUCCESS',
    REGISTER_FAILURE: 'USERS_REGISTER_FAILURE',

    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',
    
    USERS_LOGOUT_REQUEST: 'USERS_LOGOUT_REQUEST',
    USERS_LOGOUT_SUCCESS: 'USERS_LOGOUT_SUCCESS',

    GETALL_REQUEST: 'USERS_GETALL_REQUEST',
    GETALL_SUCCESS: 'USERS_GETALL_SUCCESS',
    GETALL_FAILURE: 'USERS_GETALL_FAILURE',

    POST_DELETE_REQUEST: 'POST_DELETE_REQUEST',
    POST_DELETE_SUCCESS: 'POST_DELETE_SUCCESS',
    POST_DELETE_FAILURE: 'POST_DELETE_FAILURE',
    
    POST_REQUEST: 'POST_REQUEST',
    POST_SUCCESS: 'POST_SUCCESS',
    POST_FAILURE: 'POST_FAILURE',

    GET_SIZE: 'GET_SIZE',
    GET_SIZE_FAILURE: 'GET_SIZE_FAILURE',


    GET_SINGLE_REQUEST: 'GET_SINGLE_REQUEST',
    GET_SINGLE_SUCCESS: 'GET_SINGLE_SUCCESS',
    GET_SINGLE_ERROR:    'GET_SINGLE_ERROR',

    SAVE_SINGLE_REQUEST: 'SAVE_SINGLE_REQUEST',
    SAVE_SINGLE_SUCCESS: 'SAVE_SINGLE_SUCCESS',
    SAVE_SINGLE_ERROR:   'SAVE_SINGLE_ERROR',


    UPDATE_REQUEST: 'UPDATE_REQUEST',
    UPDATE_SUCCESS: 'UPDATE_SUCCESS',
    UPDATE_ERROR:   'UPDATE_ERROR'




};
